### ISSUE TITLE
New version dont pass malware check from server

### ISSUE THREAD

**Issue by joaopequeno-git** [pubpub-zz/ppInk#145] opened 2021-09-03 09:43 UTC
Hello @pubpub-zz ,

This last version i cant download it from my server, since ZScaler block it as bellow.
Can you check it please?
![imagem](https://user-images.githubusercontent.com/56827914/131985407-d5fc259b-1048-4888-a27a-7ac3a4763ea3.png)

**Comment by pubpub-zz** [comment] 2021-09-03 13:03
Hi @joaopequeno-git,
I have been reported false positive on previous versions. I can not personnally report this to zscaler support as I do not have any account.
As an alternative, you could load the source and rebuild it.

**Comment by 3b33** [comment] 2021-09-07 08:05
Also f-secure SAFE reports like this
![image](https://user-images.githubusercontent.com/41741558/132308028-2790aaaf-8bc7-4c54-91be-b3601708c3f9.png)

**Comment by pubpub-zz** [comment] 2021-09-07 20:47
I did a many checks 
VirusTotal.com
![image](https://user-images.githubusercontent.com/4083478/132391266-f466c4a2-39a0-4a6c-b5b0-00b172293885.png)
Kaspersky
![image](https://user-images.githubusercontent.com/4083478/132392939-ba0657ce-2220-4184-bf77-843d25b44d73.png)
Trend micro
![image](https://user-images.githubusercontent.com/4083478/132397085-f5325e90-8fd7-43dc-824d-2a7d11e7b169.png)
I've send also an analysis on F-secure waiting for their report

Searching on ZScaler and F-Secure about Sandbox and the reason reported, I've seen that those reports indicate that the file has been reported based on behavior analysis. ppInk includes a webserver and also include some code to connect to OBS websocket : I do not know if those are considered as threats but those features are fully integrated in ppInk ; not sure if/how to remove this. My only solution up to now is to report ppink as false positive

**Comment by 3b33** [comment] 2021-09-08 06:04
@pubpub-zz  Good job!

Personally I'd immediately utilize a ppInk version without the suspected problematic aspects.

**Comment by pubpub-zz** [comment] 2021-09-09 11:27
@3b33 @joaopequeno-git 

I've foud a solution to remove the code at compilation.
Can you try to load those two zip and tell me about:

[ppInk_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135989/ppInk_wand09a.zip)

[ppinkS64_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135990/ppinkS64_wand09a.zip)

**Comment by joaopequeno-git** [comment] 2021-09-10 11:44
> 
> 
> @3b33 @joaopequeno-git
> 
> I've foud a solution to remove the code at compilation.
> Can you try to load those two zip and tell me about:
> 
> [ppInk_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135989/ppInk_wand09a.zip)
> 
> [ppinkS64_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135990/ppinkS64_wand09a.zip)

Still being blocked both zip files:
![imagem](https://user-images.githubusercontent.com/56827914/132848410-5a4f55fc-ab0f-48e8-8f76-91c8f7024396.png)

**Comment by pubpub-zz** [comment] 2021-09-14 11:41
> 
> 
> > @3b33 @joaopequeno-git
> > I've foud a solution to remove the code at compilation.
> > Can you try to load those two zip and tell me about:
> > [ppInk_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135989/ppInk_wand09a.zip)
> > [ppinkS64_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135990/ppinkS64_wand09a.zip)
> > @pubpub-zz
> 
> Still being blocked both zip files:
> ![imagem](https://user-images.githubusercontent.com/56827914/132848410-5a4f55fc-ab0f-48e8-8f76-91c8f7024396.png)

@joaopequeno-git 
I've tried to request some analysis by Zscaler:
https://zulu.zscaler.com/submission/a3f2f4d7-b2ed-41e5-894c-959f16d04e02
All good inhere
I've tried http://filecheck.zscaler.com/ but all the time not available

I've also tried to get analysis fron f-secure without results (I do not have this tool)
@3b33 can you give some results about the links provided.

I have no more data/ideas/support to get further. Open to any ideas

**Comment by joaopequeno-git** [comment] 2021-09-14 14:26
@pubpub-zz 

I have made the upload and its ok this file version:
![imagem](https://user-images.githubusercontent.com/56827914/133275781-c69a7392-04d9-4a98-b7a9-6bd1febddae2.png)

As i can see the file in zscaler is now downloadable.
Nice work!

**Comment by pubpub-zz** [comment] 2021-09-14 16:01
> 
> 
> @pubpub-zz
> 
> I have made the upload and its ok this file version:
> ![imagem](https://user-images.githubusercontent.com/56827914/133275781-c69a7392-04d9-4a98-b7a9-6bd1febddae2.png)
> 
> As i can see the file in zscaler is now downloadable.
> Nice work!

You are luckier than I'm . still not working for me... Can you load it through your  ZScaler gateway ?

**Comment by joaopequeno-git** [comment] 2021-09-15 11:46
> 
> 
> > @pubpub-zz
> > I have made the upload and its ok this file version:
> > ![imagem](https://user-images.githubusercontent.com/56827914/133275781-c69a7392-04d9-4a98-b7a9-6bd1febddae2.png)
> > As i can see the file in zscaler is now downloadable.
> > Nice work!
> 
> You are luckier than I'm . still not working for me... Can you load it through your ZScaler gateway ?

@pubpub-zz 

Yes i have the file downloaded from another computer, and through USB put it on the laptop. the upload was made through ZScaler gateway.

**Comment by pubpub-zz** [comment] 2021-09-15 19:11
> 
> 
> > > @pubpub-zz
> > > I have made the upload and its ok this file version:
> > > ![imagem](https://user-images.githubusercontent.com/56827914/133275781-c69a7392-04d9-4a98-b7a9-6bd1febddae2.png)
> > > As i can see the file in zscaler is now downloadable.
> > > Nice work!
> > 
> > 
> > You are luckier than I'm . still not working for me... Can you load it through your ZScaler gateway ?
> 
> @pubpub-zz
> 
> Yes i have the file downloaded from another computer, and through USB put it on the laptop. the upload was made through ZScaler gateway.

@joaopequeno-git : so for you the issue is closed with v1.8RC1 ?

@3b33 : waiting for your updates.

**Comment by joaopequeno-git** [comment] 2021-09-16 10:35
> 
> 
> > > > @pubpub-zz
> > > > I have made the upload and its ok this file version:
> > > > ![imagem](https://user-images.githubusercontent.com/56827914/133275781-c69a7392-04d9-4a98-b7a9-6bd1febddae2.png)
> > > > As i can see the file in zscaler is now downloadable.
> > > > Nice work!
> > > 
> > > 
> > > You are luckier than I'm . still not working for me... Can you load it through your ZScaler gateway ?
> > 
> > 
> > @pubpub-zz
> > Yes i have the file downloaded from another computer, and through USB put it on the laptop. the upload was made through ZScaler gateway.
> 
> @joaopequeno-git : so for you the issue is closed with v1.8RC1 ?
> 
> @3b33 : waiting for your updates.

@pubpub-zz 

Yes for me i can say the issue is for now closed.
ZScaler is not blocking it.
Thanks for the support!

**Comment by pubpub-zz** [comment] 2021-09-26 09:10
@3b33 
any updates?

**Comment by 3b33** [comment] 2021-09-26 19:35
Sorry can't check this out atm due to work load. Thank you for your effort,
I'll try to find some time soon.

**Comment by pubpub-zz** [comment] 2021-11-21 10:43
@3b33 
As the issue seems closed with joaopequeno-git, I will close the issue for the moment. Fell free to reopen it if you will have more info to provide

**Closed by pubpub-zz** 2021-11-21 10:43 UTC
