### ISSUE TITLE
ppInk keeps crashing

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#43] opened 2021-01-21 22:25 UTC
01 ,  22 ,  2021 06:23UIThreadException

version 1.4.1.23757 built on 11/01/2021 13:11
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Image format is not valid. The image file may be corrupted.
Parameter name: stream

Stack Trace:
   at System.Windows.Forms.Cursor.LoadPicture(IStream stream)
   at System.Windows.Forms.Cursor..ctor(String fileName)
   at gInk.FormCollection.getCursFromDiskOrRes(String name) in D:\gink.git\ppInk\src\FormCollection.cs:line 153
   at gInk.FormCollection..ctor(Root root) in D:\gink.git\ppInk\src\FormCollection.cs:line 589
   at gInk.Root.StartInk() in D:\gink.git\ppInk\src\Root.cs:line 376
   at gInk.Root.callshortcut() in D:\gink.git\ppInk\src\Root.cs:line 323
   at gInk.CallForm._Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\CallForm.cs:line 27
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pubpub-zz** [comment] 2021-01-22 13:11
The program seems to crash when trying to load cursor cursorarrow.cur or cursorarrow.ani or cursorarrow.ico. cursorarrow.ico is normally provided. Is the file still present and not already opened? Have you modified this file? can you provide your file ?

**Comment by JamesZing** [comment] 2021-01-22 13:47
Thank you for following up. Based on your advice, I have checked and it shows that I only have "cursorarrow.ico", which I have zipped for your verification. 
[cursorarrow.zip](https://github.com/pubpub-zz/ppInk/files/5856164/cursorarrow.zip)

As for "cursorarrow.cur" or "cursorarrow.ani", they were not included in .zip package. If you can send me these 2 other files, I can try to load them on my end to verify if this crashing issue can be resolved.

**Comment by pubpub-zz** [comment] 2021-01-22 14:00
I've checked the file and it looks good. Can you try to rename it into cursorarrrow$.cur and then restart program. You should get the default internal resource instead of the customizable external file.

**Comment by JamesZing** [comment] 2021-01-22 14:07
Yes, I have renamed the file as you mentioned but it still crashed.
Here is the file as attached:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5856304/crash.txt)

**Comment by JamesZing** [comment] 2021-01-22 14:13
In case you need this crash file to compare, here is the crash.txt when using the original cursorarrow.ico
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5856340/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-22 14:18
Which version are you using ?

**Comment by JamesZing** [comment] 2021-01-22 14:19
It should be 1.4 Alpha 1a, the latest release downloaded.

**Comment by JamesZing** [comment] 2021-01-22 14:21
By the way, you mentioned that I should "get the default internal resource instead of the customizable external file".
Please pardon me but could you kindly elaborate further?

**Comment by pubpub-zz** [comment] 2021-01-22 14:38
> Which version are you using ?
Sorry I meant which windows version ?

> By the way, you mentioned that I should "get the default internal resource instead of the customizable external file".
> Please pardon me but could you kindly elaborate further?
ppInk is customizable. for the arrow cursor, it looks for cursorarrow.cur next to ppink,exe, then it search for cursorarrow.ani, then for cursorarrow.ico. if None of them can be found, it uses an internal resource (which looks like the cursorarrow.ico I provide in the release zip)

**Comment by JamesZing** [comment] 2021-01-22 14:51
Regarding my Windows version, I am currently using Win7 Home Premium 64-bit.

Thanks for elaborating on the default internal resource, I understand now. However, based on the crash.txt files I sent to you, could it be another issue that is causing the crashes?

**Comment by JamesZing** [comment] 2021-01-22 14:55
I tried to run ppInk.exe again, this time removing the "cursorarrow.ico", hoping this will make it use an internal resource as you mentioned but I still get a crash.txt

Here it is as attached:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5856597/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-22 19:59
I'm developping ppInk under windows 10.  the Framework set normally is 4.5. Which version of .net is installed on your computer (4.8 would be nice)

**Comment by JamesZing** [comment] 2021-01-23 10:27
I see, so it is most likely a Windows compatibility issue.

Regarding MS .Net framework, I have version 4.8 installed.
![image](https://user-images.githubusercontent.com/77811611/105575581-a3905980-5da7-11eb-8513-73ed5a726e29.png)

Previously I was able to get gInk working on Win 7 but my friend encouraged me to use ppInk instead as it has a lot more functionalities.

Is there any workaround to get ppInk working under Win 7?

**Comment by pubpub-zz** [comment] 2021-01-23 11:18
I agree  but I've retried ppInk latest release in a win 7 pro release (provided by microsoft) and the program ran correctly.
I've recompiled ppInk enforcing .net 4.8 framework :
[ppInk dotNet4.8.zip](https://github.com/pubpub-zz/ppInk/files/5860083/ppInk.dotNet4.8.zip)
Can you try it ?

**Comment by JamesZing** [comment] 2021-01-23 11:38
Thanks a lot, I ran it but an error message still popped up.

Here is the latest crash.txt file after running your latest compiled version (ppInk dotNet4.8):
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860110/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-23 11:47
rename the cursorarrow.ico to cursorarrow$.ico

**Comment by JamesZing** [comment] 2021-01-23 12:00
Thanks for the suggestion, I tried that.

There is still an error message:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860148/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-23 12:22
rename also the cursoreraser.ico to cursoreraser$.ico

**Comment by JamesZing** [comment] 2021-01-23 12:46
It works! 

Thanks for the workaround!

I will test out the features and update you if I find anything.

Thanks again for helping to troubleshoot.

**Comment by pubpub-zz** [comment] 2021-01-23 14:13
I've made an extra mod to handle image/cursor loading exceptions : This version should not require to delete the files but should still work
[ppInk (2).zip](https://github.com/pubpub-zz/ppInk/files/5860315/ppInk.2.zip)
can you test it please

**Comment by LucasMNP** [comment] 2021-01-23 15:00
Did you unzip ppInk somewhere that requires admin permissions (such as Program Files)? Try unpacking it somewhere else and try again.

**Comment by JamesZing** [comment] 2021-01-23 15:12
> 
> 
> I've made an extra mod to handle image/cursor loading exceptions : This version should not require to delete the files but should still work
> [ppInk (2).zip](https://github.com/pubpub-zz/ppInk/files/5860315/ppInk.2.zip)
> can you test it please

Hi pubpub-zz, I just tested your latest version, this version works well without any user intervention and there was no error pop-up. However, I noted that there is still a crash.txt generated. I have attached it for your further investigation:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860389/crash.txt)

**Comment by JamesZing** [comment] 2021-01-23 15:18
> 
> 
> Did you unzip ppInk somewhere that requires admin permissions (such as Program Files)? Try unpacking it somewhere else and try again.

Hi LucasMNP, I unzipped ppInk in the "Downloads" folder which is the default for Win7. 

To the best of my knowledge, this folder should not require admin permissions.

Nevertheless, I tried your suggestion and unzipped the version "1.4 Alpha 1a" to test it out but I still encountered the crash error as mentioned previously at the start of this thread.

**Comment by JamesZing** [comment] 2021-01-23 15:34
> 
> 
> I've made an extra mod to handle image/cursor loading exceptions : This version should not require to delete the files but should still work
> [ppInk (2).zip](https://github.com/pubpub-zz/ppInk/files/5860315/ppInk.2.zip)
> can you test it please

Update: Upon clicking "Add Text" icon, the program crashes.

Attached is the latest crash.txt isolating this issue (previous crash.txt was deleted first before repeating steps for this issue):
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860416/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-23 15:40
> Hi pubpub-zz, I just tested your latest version, this version works well without any user intervention and there was no error pop-up. However, I noted that there is still a crash.txt generated. I have attached it for your further investigation:
> [crash.txt](https://github.com/pubpub-zz/ppInk/files/5860389/crash.txt)

this is normal, I've prefered to leave some debug traces if cursor files can not be loaded. They are written quietly in the crash.txt file. Behavior is as expected.

**Comment by pubpub-zz** [comment] 2021-01-23 15:42
> Did you unzip ppInk somewhere that requires admin permissions (such as Program Files)? Try unpacking it somewhere else and try again.

Hi @LucasMNP,
have you got issues on your side ?

**Comment by JamesZing** [comment] 2021-01-23 15:59
> 
> 
> > I've made an extra mod to handle image/cursor loading exceptions : This version should not require to delete the files but should still work
> > [ppInk (2).zip](https://github.com/pubpub-zz/ppInk/files/5860315/ppInk.2.zip)
> > can you test it please
> 
> Update 1 : Upon clicking "Add Text" icon, the program crashes.
> 
> Attached is the latest crash.txt isolating this issue (previous crash.txt was deleted first before repeating steps for this issue):
> [crash.txt](https://github.com/pubpub-zz/ppInk/files/5860416/crash.txt)

Update 2 : Pressing "Alt-Tab" OR "Ctrl-Alt-G" will cause the program to crash. I replicated both issues separately. Here are their attached Crash.txt files.

(a) Attached Crash.txt when pressing "Alt-Tab":
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860444/crash.txt)

(b) Attached Crash.txt when pressing "Ctrl-Alt-G":
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860447/crash.txt)

This led me to suspect that pressing "Alt" key alone will cause the program to crash. I tested this out and it does seem that "Alt" key is responsible for the crashes.

(c) Attached Crash.txt when pressing "Alt" key alone:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860461/crash.txt)

**Comment by JamesZing** [comment] 2021-01-23 16:03
> 
> 
> > Hi pubpub-zz, I just tested your latest version, this version works well without any user intervention and there was no error pop-up. However, I noted that there is still a crash.txt generated. I have attached it for your further investigation:
> > [crash.txt](https://github.com/pubpub-zz/ppInk/files/5860389/crash.txt)
> 
> this is normal, I've prefered to leave some debug traces if cursor files can not be loaded. They are written quietly in the crash.txt file. Behavior is as expected.
> 
> To prevent crash reports, just delete/rename the cursorarrow.ico and cursoreraser.ico

Thanks pubpub-zz for the clarification.

Following your advice, I have deleted these 2 files ("cursorarrow.ico" and "cursoreraser.ico") to continue with the testing of the features.

**Comment by pubpub-zz** [comment] 2021-01-23 16:11
When pressing Alt, the 'hint cursor' drawing cursor is replaced with the arrow. the crash occured at that moment.

> Following your advice, I have deleted these 2 files ("cursorarrow.ico" and "cursoreraser.ico") to continue with the testing of the features.
the crash is still reported with the ico files deleted ?

**Comment by JamesZing** [comment] 2021-01-23 16:34
> 
> 
> When pressing Alt, the 'hint cursor' drawing cursor is replaced with the arrow. the crash occured at that moment.
> 
> > Following your advice, I have deleted these 2 files ("cursorarrow.ico" and "cursoreraser.ico") to continue with the testing of the features.
> 
> the crash is still reported with the ico files deleted ?

Yes, I deleted the files "cursorarrow.ico" and "cursoreraser.ico" (as well as any previous crash.txt), emptied my Recycle Bin, then re-tested each scenario:

Even with "cursorarrow.ico" and "cursoreraser.ico" deleted, the following will cause the program to crash:

(a) When adding text
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860541/crash.txt)

(b) When "Alt" key is pressed
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860542/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-23 16:50
can you try to add those two files in ppink folder :
[cursors4w7.zip](https://github.com/pubpub-zz/ppInk/files/5860568/cursors4w7.zip)

**Comment by JamesZing** [comment] 2021-01-23 17:03
> 
> 
> can you try to add those two files in ppink folder :
> [cursors4w7.zip](https://github.com/pubpub-zz/ppInk/files/5860568/cursors4w7.zip)

I have added both files to ppInk folder and repeated the tests, the following crashes still occurred:

(a) When adding text
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860593/crash.txt)

(b) When "Alt" key is pressed
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5860595/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-23 17:15
I've generated a version which is relying on 'default' cursors.
[ppInk NoCurs.zip](https://github.com/pubpub-zz/ppInk/files/5860627/ppInk.NoCurs.zip)
can you tell me if it fixes your issue ?

**Comment by JamesZing** [comment] 2021-01-23 17:35
Your latest version works beautifully, thank you.

Unlike its predecessors, "ppInk NoCurs.zip" no longer crash in Win7.

I have a question, how may we customise the hotkey to return to Normal Cursor.
The default is "Ctrl+Alt+G", but "Right-Click" would be more intuitive.

Thanks again for your beautiful work and tireless troubleshooting.

**Comment by pubpub-zz** [comment] 2021-01-23 17:48
Good !
In next versions I will include a way to force the systems cursors.

the shortcut Ctrl+Alt+G is the common for 1st call, go to /return from pointer(arrow) mode. it has therefore to be a shortcut.
An alternative is to use alt+tab. on click on the arrow which is not too far away from right click.

about autoclose when selecting normal cursor, you can disable it in options "Engage Pointer and auto-fold with alt+tab".

**Comment by JamesZing** [comment] 2021-01-23 17:59
Wonderful, I have followed your advice and disabled the option "Engage Pointer and auto-fold with alt+tab".
Yes, I find the alternative "Alt-Tab" much easier to press, thanks for adding this alternative.

2 quick questions:
(a) Is there a way to set the default color and width for Pen 1?
(b) Is there a list of fonts that work with ppInk besides "Comic Sans MS"?

**Comment by pubpub-zz** [comment] 2021-01-23 18:24
all can be configured through the option dialog box. 
color : click on the color to adjust color/transparency/size
![image](https://user-images.githubusercontent.com/4083478/105610550-7005fd00-5db0-11eb-8c18-1dd55d32299d.png)

![image](https://user-images.githubusercontent.com/4083478/105610546-69778580-5db0-11eb-8610-a6f918d2e2cc.png)

font 
![image](https://user-images.githubusercontent.com/4083478/105610585-a2aff580-5db0-11eb-8514-fcc661c09556.png)

shortcuts
(including the Ctrl+Alt+G that you can make easier too like ctrl+G but remember it is a windows global shortcut that you are setting.

**Comment by JamesZing** [comment] 2021-01-23 18:55
Cool!

I followed your advice and managed to configure the necessary.

Regarding the images that you kindly provided, such as "happy.png", "neutral.png", "sad.png", is there a way for them to show up as icons in the toolbar?

**Comment by pubpub-zz** [comment] 2021-01-23 19:39
not for the moment, but it is an idea. can you open a new issue to keep track of it as we can now close this issue.

do not hesitate to star the project and make promotion of it😀

**Comment by JamesZing** [comment] 2021-01-23 19:44
> 
> 
> not for the moment, but it is an idea. can you open a new issue to keep track of it as we can now close this issue.
> 
> do not hesitate to star the project and make promotion of itgrinning

Will do, thanks again for your great support and troubleshooting!

**Comment by pubpub-zz** [comment] 2021-01-23 20:18
I'm sorry to  bother you but you are my only way to test my mods:
can you try this version
[ppInk (2).zip](https://github.com/pubpub-zz/ppInk/files/5860992/ppInk.2.zip)

**Comment by JamesZing** [comment] 2021-01-25 02:29
No worries, I am happy to help you test out your mods.

I just tested "ppInk (2a).zip"

Seems like the old issue is not resolved with this version, it will still crash in Win7 when trying to 
(a) Add Text (T)
(b) Edit Text (M)
(c) Numbered Chip (N)
(d) Move/Pan Drawings (G)

As "ppInk.NoCurs" has resolved these 4 issues, I believe the above 4 issues are linked in "ppInk (2a)", hence I only attached the Crash File when trying to Add Text (T) alone for your further diagnosis:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5863794/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-25 12:25
new attempt. You are right those four issues have the same root cause. Can you confirm that you have no issue when using the erasor and the snapshot(camera)
[ppInk (3).zip](https://github.com/pubpub-zz/ppInk/files/5866482/ppInk.3.zip)
You will also be able to alpha test my proposal for the clipart 'shortcuts' (they can be customized with long click on the tool) in the toolbar 😄

**Comment by JamesZing** [comment] 2021-01-25 15:37
In testing version "ppInk (3)", no crash occurred at all.

Each function was thoroughly tested, including Eraser (E), Snapshot (K) as well as the newly-added "Handwriting" tools for clipart. (The only function I yet to test is the "Video Recording" function.)

Besides that, everything is working as intended. Great work!

I have 2 suggestions:
(a) In Eraser (E) mode, it would be helpful if the drawing can be boxed up (or highlighted) to indicate to the user which drawing is to be erased.
(b) For the Clipart function (the newly added handwriting tools), it can be more user-friendly by letting a user choose to pre-set the size and simply left-click to add; just like the Numbered Chip (N) function.

Once again, thanks for the great work with "ppInk (3)".

**Comment by JamesZing** [comment] 2021-01-25 18:21
In addition to the 2 suggestions in previous post, the "Moving function (P)" can also be greatly improved.

(a) Clicking "once" is designed for "Moving one drawing".
Actual Usage: Not easy as there is no way to tell if which drawing is actually being selected for moving.
Suggestion: When in "Moving Mode", if a cursor is hovering over a drawing, highlight or box up the drawing to indicate to the user which drawing can be moved.

(b) Clicking "twice" is designed for "Copying one drawing".
Actual Usage: Also not easy as there is no way to tell if a drawing is being selected for copying. Also as there is no "Paste button", unless the user is familiar with "Ctrl+V", he/she will get stuck after copying.
Suggestion: When in "Moving Mode", if a cursor is hovering over a drawing, highlight or box up the drawing to indicate to the user which drawing can be copied (and pasted).

(c) Clicking "thrice"  is for "Moving all drawings".
Actual Usage: This works well as everything gets selected for you.
Suggestion: None.

**Comment by pubpub-zz** [comment] 2021-01-25 23:18
your new proposal are quite tricky to implement... Checking for feasability. can you transfer those proposal in a new issue : this one can be closed now as changes are commited

**Comment by JamesZing** [comment] 2021-01-26 04:48
Definitely, I will create them as a new issue for you.

**Comment by JamesZing** [comment] 2021-01-26 06:20
Update with regards to version "ppInk (3)"

A crash just occurred. I am unsure what caused it as I could not replicate it. 

Nevertheless I have attached the corresponding crash.txt file for further investigations:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5871523/crash.txt)

**Comment by pubpub-zz** [comment] 2021-01-27 23:05
latest crash is new. I've added robustification

**Comment by pubpub-zz** [comment] 2021-02-19 20:21
I will close this issue, if you have more information use #46 or #47

**Closed by pubpub-zz** 2021-02-19 20:21 UTC
