### ISSUE TITLE
Error after trying to use clipboard image

### ISSUE THREAD

**Issue by Billord73** [pubpub-zz/ppInk#273] opened 2023-09-04 09:28 UTC
<img width="210" alt="image" src="https://github.com/pubpub-zz/ppInk/assets/144008209/e3112cb1-7896-4aac-ac30-d3b76581fc4f">

> Can you please clarify how you've got there.

I click the clip art button, then I click "from clipboard" and select the image and click insert.

This only happens if I try to use clipboard images. Loading from file storage or using the built-in pictures works as intended.

**Comment by pubpub-zz** [comment] 2023-09-04 11:56
Can you please clarify how you've got there.

**Comment by pubpub-zz** [comment] 2023-09-04 18:15
"from clipboard" is to be used when you have directly an image in your clipboard, not an image file you have placed in your clipbard. Can you please confirm this behaviour

**Comment by Billord73** [comment] 2023-09-04 18:46
The image in the clipboard is one from the win + shift + s snip tool

**Comment by pubpub-zz** [comment] 2023-09-04 19:30
got it : it is a duplicate of #222
already fixed
I've been able to release it yet officially but you can get it in this beta:
https://github.com/pubpub-zz/ppInk/files/12018083/ppInk_offsetCliparts.zip

**Closed** 2023-09-04 19:30 UTC
