### ISSUE TITLE
Clip arts not saving

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#84] opened 2021-05-03 09:09 UTC
Hey there! When I'm loading a clip art to version 1.5RC2 it doesn't get saved. Previously, in version 1.4, after adding a clipart I could save the settings to file and it'd stay there. However, back then it always imported at low resolution. Version 1.5 imports pictures at the correct resolution but they aren't persistent.

**Comment by pubpub-zz** [comment] 2021-05-03 11:20
In order to get persistance on the list of Cliparts, you have to modify the list through the option dialogs and then save config.ini . When adding images directly in the clipart dialog opened through the toolbar, you will only add them for the time of the session.

**Comment by NOVAinc** [comment] 2021-05-03 17:06
> In order to get persistance on the list of Cliparts, you have to modify the list through the option dialogs and then save config.ini . When adding images directly in the clipart dialog opened through the toolbar, you will only add them for the time of the session.

It works now! Thanks a lot. However, adding them through the clipart menu used to save them for the full session in 1.4. Now it only adds them at the time of loading an image and then even during that session they will disappear. I have now used the Options dialog to make them persistent, but I think it's still bugged due to them not sticking around for the entire session right? In any case, I managed to get them. Thanks :)

I couldn't find a paypal anywhere. Are you taking donations for your project? I don't have a lot of money but I use it extensively and I'd like to help with a bit at least.

**Comment by pubpub-zz** [comment] 2021-05-03 18:53
> I have now used the Options dialog to make them persistent, but I think it's still bugged due to them not sticking around for the entire session right? In any case, I managed to get them. Thanks :)

Can you clarify what you mean by not sticking around ? can you make a video ?

> I couldn't find a paypal anywhere. Are you taking donations for your project? I don't have a lot of money but I use it extensively and I'd like to help with a bit at least.

I'm so confused :You are the first one to propose me donation ; I did not think about this development to get some money, so what I propose is to give your donation to support education in the world (eg https://plan-uk.org/); what you can do for me personnally is to star my project 😉.

May I also ask you how you are using the program : presentation? screen annotation for documents building? others?

**Comment by NOVAinc** [comment] 2021-05-04 00:56
Thanks a lot for your answer. Here is what I mean

**Comment by NOVAinc** [comment] 2021-05-04 01:15
Thanks a lot for your answer!

This is what I mean by cliparts not staying for the rest of the session. They're only persistent when the toolbar is extended after you added them, but if you collapse it and extend it back up they disappear. In version 1.4 they used to stay there until you closed the program fully I believe. I've uploaded a video file demonstrating the problem https://we.tl/t-5wtGiLS0rl

I am an aspiring Age of Empires 2 matches commentator from Argentina and I use annotations during my streams to talk about map generation, positioning and overall strategizing. Having different pen configurations allows me to match the annotations to the player color, and clip art functionality allows me to stamp stone fortification doodles quickly when talking about map control :)

I love your software and I was actually gonna use Epic Pen but I decided to look for alternatives first. I'm super glad I did, and I love that this is open source since I'm also an extensive GIMP and Blender user. I'm looking forward to implement the zoom functionality but I need to get through a few hurdles first. I'm also facing some UI thread errors that I'll report later if I get them again as well as a few other small things, but overall I'm very happy with this solution currently! Here is a VOD from my stream earlier today if you want to take a look at how I integrate the software into it.
https://www.twitch.tv/videos/1009866052?t=2h59m49s

**Comment by pubpub-zz** [comment] 2021-05-04 08:16
Thanks for your demonstration. This is great and the rendering is wonderfull. It allows me to notice that ppInk handles correctly variable width with stylus. Can I use your link to give a demonstration of what can be done with OBS ?

About your point, This what I've coded the 'session' time I was talking about is one inking session. At the origin, I wanted this duration, but I agree that now, it may be better for extend it and add a 'reset list' button. I will create an issue. can you subscribe to it ? I will certainly need your evaluations.

About UI errors, waiting for your crash text. Many fixes are in the pipe, but I have a regression I need to fix first (see latest posts in #75)

**Comment by NOVAinc** [comment] 2021-05-04 08:32
I'm not too well versed with GitHub but I'll try to get around. You may certainly use the video I shared for anything you want, but bear in mind Twitch's VODs disappear after 14 days. If you want to save it you'd need to create a clip. If you don't know how, let me know and I can get that done. I'll check for the issue and I'll subscribe to it! Usually I'm on stream when I use the tool so I don't have the time to gather the crash info. Can I access the log after I've had to restart the program? Let me know if I should provide just the text content or the file itself.

**Comment by pubpub-zz** [comment] 2021-05-04 09:29
You are reporting lots of crashes. I see most (all ?) - aspecially the out of memory - should be solved in the next release
You may have a try to this beta version:
[ppInk64_25a.zip](https://github.com/pubpub-zz/ppInk/files/6372030/ppInk64_25a.zip) (from #75 exchanges)
It has been reported that randomly some shapes(arrow / rectangle / ...) are dissapearing just after drawing.
If you have a little a time, can you this version. if you also note some shapes dissapearing, let me know.
PS : I've been able to get the clip when you are adding the castle on the island. Your use of the tool is great!

**Comment by NOVAinc** [comment] 2021-05-04 22:50
I have tested the new version you sent. I didn't experience issues with shapes but I can test it more extensively during my streams in the next few days. One issue I did get though is I can't use the zoom feature, which brings the UI error. When this error message pops up it presents 3 buttons, none of which allows you to keep using the program and requires a force quit using the task manager. While this sign is up, the zoom area is displayed as a black square with a red cross on it that follows the cursor around. Should I make a different report for this one? I'm not sure since it's not from a release version. Thanks for your help

**Comment by pubpub-zz** [comment] 2021-05-05 12:44
Thanks for this bug  report.
This release introduced a hudge rework which is the source of the errors/regression (Zoom, Erasor) you are reporting
I will change the behavior of the crash report : 
   * Save the strokes for recovery in the autosave.strokes.txt
   * propose 2 buttons : one to try to continue (just in case it works) an abort button to quit the application
 The zoom with the red cross is a secondary effect of the error at the origini of the UI crash reported.
For the erasor, this is also due to code rewriting. I will fix it too
Will come back soon with a new beta version.

**Comment by pubpub-zz** [comment] 2021-05-05 21:58
I've normally fixed the window and the eraser and also the crash window buttons but I hope that you will not be able to see that 😊
[ppInk64_05a.zip](https://github.com/pubpub-zz/ppInk/files/6430465/ppInk64_05a.zip)

**Comment by NOVAinc** [comment] 2021-05-05 23:09
Thanks for the update! I'll be testing it tomorrow during the stream. Today I tested yesterday's version and everything worked well except 2 things:
- Drawing in progress window seemed to change somehow since I needed to keep on retargetting the window in OBS while this wasn't the case before. I mean I had to target a different window using window capture and then re-select Drawing in progress for it to start showing again. I'll see if it still happens with this one.
- When drawing with the pens, the traces would look good during tracing (different line width according to how much pressure was being put on the pen), but after lifting the pen they would turn to single width as if I had used the mouse. I'm not sure if this might be related to me using a pen file from version 1.4 in which I had all my pens set up, but I'll try with the new version configuring one from scratch.

**Comment by pubpub-zz** [comment] 2021-05-06 06:47
I will left onside point one as you have found the solution. about point 2 (width vs pressure), I think I know why : I assume this is due to some attempt to better manage numerous strokes. My Problem, is I do not have a stylus for testing. can you do me a favor : can you draw 3 to 5  strokes with variable length, ans save them in a file to send me I do not know how the data are stored in.

Meanwhile I will prepare  a new version.

**Comment by pubpub-zz** [comment] 2021-05-06 13:43
I've removed the change that should have induced regression on the stylus pressure
[ppInk64_06a.zip](https://github.com/pubpub-zz/ppInk/files/6435002/ppInk64_06a.zip)

Tell me if it is OK like that

**Comment by NOVAinc** [comment] 2021-05-06 17:19
I have tested the previous built you shared followed by the new build. The new build retains width after lifting the pen, while the previous version shows correct width while tracing but gets uniform when lifting the pen. I've included a video test as well as both stroke files here

https://we.tl/t-4j9Ypz5s9x

**Comment by pubpub-zz** [comment] 2021-05-06 21:35
Thanks for data and video

**Comment by pubpub-zz** [comment] 2021-05-17 08:05
@NOVAinc,
can you have a look to #86. problem is normally solved

**Comment by pubpub-zz** [comment] 2021-05-29 13:14
For me all is done inhere, I propose to close this issue

**Closed** 2021-05-29 22:10 UTC
