### ISSUE TITLE
Issue with multiple screens - with different %scale zooms and with 3 screens

### ISSUE THREAD

**Issue by Pat075** [pubpub-zz/ppInk#309] opened 2024-08-22 23:10 UTC
Hi

(I am using windows 11, up to date, and ppink v1.9.0)

I noticed that when I have two screens they must have the same %scale parameter on each (100%, 125%, 150%,...) otherwise the spot on the screen is shifted from the place where I put the finger on a touchscreen (the second screen).

I also could not have ppink work with 3 screens, even with the same resolution and same scale parameter, the drawings were appearing on the main screen when I was touching the second one, the third one being untouched. A drawing with the mouse could sometimes be on the right screen but having strange mouvements, and the finger on the screen never worked.

Is there a way to organize the screens so that ppink works with 3 screens ? Did I misconfigure something ? I tried to align them in the windows 11 parameters but it did not change anything.

Otherwise thank you for this tool, I like it very much and I often use it to show things to friends by sharing my screen! It is great!

Thanks for your help!

**Comment by pubpub-zz** [comment] 2024-08-23 07:04
try this trick:
https://github.com/pubpub-zz/ppInk?tab=readme-ov-file#tips

**Comment by pubpub-zz** [comment] 2024-08-26 15:25
@Pat075 
I assume the problem is solved. I close it. feel free to ask to re open it if needed

**Comment by Pat075** [comment] 2024-09-13 22:46
Yes it is closed. I did not see the fix, thaks a lot for your help ! ;)

**Closed** 2024-09-14 07:01 UTC

**Comment by pubpub-zz** [comment] 2024-09-14 07:06
@Pat075 
do not hesitate to star the project 😉
