### ISSUE TITLE
Crash UIThreadException

### ISSUE THREAD

**Issue by bobsmith444** [pubpub-zz/ppInk#68] opened 2021-03-13 17:13 UTC
I'm getting the following crash report. Can you help?

11 / 09 / 2020 23:03UIThreadException

Oops, gInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'Button'.

Stack Trace:
   à System.Windows.Forms.Control.CreateHandle()
   à System.Windows.Forms.Control.get_Handle()
   à System.Windows.Forms.Control.PointToScreen(Point p)
   à System.Windows.Forms.ContextMenu.Show(Control control, Point pos, Int32 flags)
   à System.Windows.Forms.ContextMenu.Show(Control control, Point pos)
   à System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   à System.Windows.Forms.Control.WmContextMenu(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

11 / 10 / 2020 19:02UIThreadException

Oops, gInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Le fichier spécifié est introuvable

Stack Trace:
   à System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start()
   à gInk.FormCollection.VideoRecordStartFFmpeg(Rectangle rect) dans D:\gink.git\ppInk\src\FormCollection.cs:ligne 2718
   à gInk.FormDisplay.timer1_Tick(Object sender, EventArgs e) dans D:\gink.git\ppInk\src\FormDisplay.cs:ligne 620
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pubpub-zz** [comment] 2021-03-13 18:26
many fixes have been introduced since this date. Can you try with the latest versions Can you upgrade to the latest version. If the error still occurs, can you also tell a little more about the latests actions

Thanks.

**Comment by pubpub-zz** [comment] 2021-03-14 15:10
note : just looking at the second exception, il looks like you have not install ffmpeg

**Comment by pubpub-zz** [comment] 2021-03-23 12:43
hi @bobsmith444,
     have you been able to try release 1.5 ?

**Comment by pubpub-zz** [comment] 2021-04-01 10:51
> 
> 
> hi @bobsmith444,
> have you been able to try release 1.5 ?

any results to share?

**Comment by grcstudent** [comment] 2021-04-08 04:01
I am also getting UThread Exception. I am posting the screenshot of the error. I downloaded the latest version as of today 4/7/21. Can you help?

![pping-UThread-2021-04-07](https://user-images.githubusercontent.com/81730319/113966710-75d28280-97e4-11eb-88cb-f2186ee250e6.png)

**Comment by pubpub-zz** [comment] 2021-04-08 05:57
Hi @grcstudent 
Can you please provide the full crash.txt file from.ppink folder for analysis
Can you also indicate if you have remove/change /add files in this folder. 
Thanks

**Comment by pubpub-zz** [comment] 2021-04-08 21:49
the problem is due to stamp file which are missing. immediately you can reset the config.ini to the original and it should work

**Comment by grcstudent** [comment] 2021-04-09 00:00
Please find the crash.txt attached here. The crash happened right away before I had a chance to work with the config ini file.
Thank you.
[crash.txt](https://github.com/pubpub-zz/ppInk/files/6282318/crash.txt)

**Comment by pubpub-zz** [comment] 2021-04-09 06:36
You seem to have built/compile ppInk by your own. can you compare your ppink folder with the prebuilt version available in releases

thx

**Comment by pubpub-zz** [comment] 2021-04-15 19:59
hi @bobsmith444,
> > have you been able to try release 1.5 ?
> 
> any results to share?

+1 ....

**Comment by pubpub-zz** [comment] 2021-04-15 20:00
@grcstudent 
> 
> 
> You seem to have built/compile ppInk by your own. can you compare your ppink folder with the prebuilt version available in releases
> 
> thx
Have you found any discrepancy ?

**Comment by pubpub-zz** [comment] 2021-04-27 11:28
@grcstudent
any news to add ?

**Comment by pubpub-zz** [comment] 2021-05-09 21:37
@bobsmith444  / @grcstudent,
without any activity, I will close this issue

**Comment by pubpub-zz** [comment] 2021-05-16 22:50
I close the issue, feel free to reopen it if you have updates

**Closed by pubpub-zz** 2021-05-16 22:50 UTC
