### ISSUE TITLE
Eraser (E) & Moving (P) Functions - Selection Visibility (Box or Highlight)

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#47] opened 2021-01-26 06:03 UTC
In these 2 modes, there are currently no clear indication as to which drawing would be erased or moved.

Suggestion for improvement: Highlight / Box up the drawing to be erased or moved.

**Comment by pubpub-zz** [comment] 2021-01-26 22:54
This is a first alpha version with selection implemented.
[ppInk Select Alpha1.zip](https://github.com/pubpub-zz/ppInk/files/5876617/ppInk.Select.Alpha1.zip)

**Comment by pubpub-zz** [comment] 2021-01-27 23:11
new beta release available with all latest mods (clipart button / text framing / Selection visibility / numbering size independant from text
[ppInk Beta.zip](https://github.com/pubpub-zz/ppInk/files/5883694/ppInk.Beta.zip)

**Comment by JamesZing** [comment] 2021-01-30 04:14
Cool, I have tested ppInk Beta.

With regards to the Selection visibility for Eraser (E) and Moving (P) modes, I dont see any boxing or highlighting on my end for Win7. Maybe it's only visible on Win10?

**Comment by pubpub-zz** [comment] 2021-01-30 11:33
this is what you should get :
![image](https://user-images.githubusercontent.com/4083478/106355297-3aed3380-62f7-11eb-97fe-9cbb14bed4ef.png)

The border is normally one pixel wide What is your screen resolution ?

**Comment by JamesZing** [comment] 2021-01-30 16:10
I am using a multiple monitor setup and my primary monitor for testing is 1920 x 1080.

Now that I see what's on your end, I looked out for a selection border.
This is when I discovered something peculiar.
The selection border is actually there but it's not where the drawing/text is. 
Instead, it is offset to the bottom right.

To demonstrate this, I typed something, selected Eraser (E) then took a screenshot for you (Note; My Eraser cursor is hovering over the text but it is not captured during the screenshot):
<img width="1058" alt="Selection Border when Erasing" src="https://user-images.githubusercontent.com/77811611/106361407-b0d5b700-6358-11eb-9ace-107998a20254.png">

**Comment by pubpub-zz** [comment] 2021-01-30 17:42
can you redo the test with a hand writing

**Comment by JamesZing** [comment] 2021-01-30 17:59
I redo the test with a handwriting.

I was able to erase but there was no selection border.

**Comment by pubpub-zz** [comment] 2021-01-30 18:04
Can you try this version with both text and stroke:
[ppInk (3).zip](https://github.com/pubpub-zz/ppInk/files/5898446/ppInk.3.zip)

if still offsetting, can you disconnect your secondarty screen and redo the test

**Comment by JamesZing** [comment] 2021-01-30 18:16
I tested this latest version of "ppInk (3)".

Here's the verdict: 
(a) For Text, Selection Border is visible & there is no offsetting. Perfect!
(b) For Handwriting, Selection Border is completely absent, not even an offset. Not good.

**Comment by pubpub-zz** [comment] 2021-01-30 19:19
> if still offsetting, can you disconnect your secondarty screen and redo the test

can you do this test too.
also, can you add frame around the text.

**Comment by JamesZing** [comment] 2021-01-30 19:36
Yes, I just tried to repeat the test with only one screen and it still does not work for Handwriting, no Selection Border seen.

Regarding "adding a frame around the text", can you clarify what you meant? (By the way, for Text, it already works perfectly. There is a Selection Border when my cursor hovers the Text and there is no offset, so it's working perfectly for Text.)

**Comment by pubpub-zz** [comment] 2021-01-30 19:39
like this
![image](https://user-images.githubusercontent.com/4083478/106366311-4b270200-633b-11eb-8a11-57122f1180d7.png)

**Comment by JamesZing** [comment] 2021-01-30 19:54
Ok, this does not look too good.

With "Frame + Transparent background" selected, I get the following:
<img width="913" alt="ppInk (3); Text Function Test with ''Frame + Transparent Background''" src="https://user-images.githubusercontent.com/77811611/106366606-f8b80680-6377-11eb-9aa9-d4dc247bcbd2.png">

**Comment by pubpub-zz** [comment] 2021-01-31 13:09
This is a version with some new tools to be used for debug:
[ppInk (4).zip](https://github.com/pubpub-zz/ppInk/files/5899728/ppInk.4.zip)

can you reproduce the following image:
![image](https://user-images.githubusercontent.com/4083478/106384845-5cb8ea00-63cd-11eb-92e0-7dad8fe69045.png)
Normally the magnetic effect should work can you confirm it ?
When all drawings can you press the disk button : it will create a ppinkSav.txt can you send it.

**Comment by JamesZing** [comment] 2021-01-31 13:59
Yes I was able to re-create your drawing.

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/77811611/106386227-f1900780-640e-11eb-961b-220974d261e6.png">

p.s. The numbered chip seems small only because I left all settings as default.

Yes, the magnetic effect works.

Attached is the ppInkSav.txt as requested (I have to zip it otherwise it will not allow me to attach):
[ppinkSav.txt.zip](https://github.com/pubpub-zz/ppInk/files/5899856/ppinkSav.txt.zip)

**Comment by pubpub-zz** [comment] 2021-01-31 15:22
Thks but there seems to be a mistake : it is not the good file

**Comment by pubpub-zz** [comment] 2021-02-01 12:43
I've prepared a new version : can you try it (same drawing as before please)
[ppInk (5).zip](https://github.com/pubpub-zz/ppInk/files/5903972/ppInk.5.zip)

(same drawing as before please)
With this version, the saved file is AutoSave.strokes.txt in %userprofile%\Pictures\gink
can you check also selection and moving object

            Thks

**Comment by JamesZing** [comment] 2021-02-05 19:19
I was about to do the test when the app kept crashing.

[crash.txt](https://github.com/pubpub-zz/ppInk/files/5934773/crash.txt)

**Comment by pubpub-zz** [comment] 2021-02-05 20:12
the program tries to create the autosave strokes:

a) can you check that C:\Users\Win7\Pictures\gInk 
b) can you check C:\Users\Win7\Pictures\gInk\AutoSave.strokes.txt  is not opened by another program

**Comment by JamesZing** [comment] 2021-02-06 03:11
Yes, I made sure to restart Windows before performing the test.
I even close the window of ppInk.5 after opening the program to make sure that Explorer.exe is not accessing the entire folder in anyway.

Even then, the program kept crashing.

One of the triggers is when I click on the "X" on the toolbar to exit the program.
Whenever I do this, the program will surely crash.

How about using a previous version without the "AutoSave.strokes.txt" (e.g. ppInk.4) and find another way to save the info you need?

**Comment by pubpub-zz** [comment] 2021-02-07 23:01
I've robustified the creation. 
[ppInk beta.zip](https://github.com/pubpub-zz/ppInk/files/5940208/ppInk.beta.zip)
If you still have an issue, change the destination folder :
![image](https://user-images.githubusercontent.com/4083478/107161989-a5117280-69a0-11eb-9276-6840127f0b62.png)

**Comment by pubpub-zz** [comment] 2021-02-14 16:24
Can you check the latest version below 
[ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5978019/ppInkZoom.zip)

a) do you still have problem about selection not being correct during deletion ?
b) can you provide the autosave.strokes.txt

Thx

**Comment by pubpub-zz** [comment] 2021-02-23 23:01
> 
> 
> Can you check the latest version below
> [ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5978019/ppInkZoom.zip)
> 
> a) do you still have problem about selection not being correct during deletion ?
> b) can you reproduce drawing as discussed ealier([#47 (comment)](https://github.com/pubpub-zz/ppInk/issues/47#issuecomment-770386712)) and provide the autosave.strokes.txt
> 
> Thx

Any progress in your tests?

**Comment by pubpub-zz** [comment] 2021-03-05 22:07
@JamesZing 

> > Can you check the latest version below
> > [ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5978019/ppInkZoom.zip)
> > a) do you still have problem about selection not being correct during deletion ?
> > b) can you reproduce drawing as discussed ealier([#47 (comment)](https://github.com/pubpub-zz/ppInk/issues/47#issuecomment-770386712)) and provide the autosave.strokes.txt
> > Thx
> 
> Any progress in your tests?

+1

**Comment by pubpub-zz** [comment] 2021-03-16 07:20
Hi @JamesZing,
Without feed backs  I will close this issue for issue tracking clarification. Do not hesitate to reopen it when you will have new information.

**Closed by pubpub-zz** 2021-03-16 07:20 UTC
Labels: enhancement
